# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 792d6659c1302545b805dd2ff064d7c7e2dd4d78ccd3032fc1c9e9290165b9f3c3bf6188bc9702c18f0e51a84d0f414c40fcaa568723b2e926156c103eaa7e79

test:
  secret_key_base: 452cc3622e22b4b8d69c5581ee126535be36579ced7f083392ab1958ca96023b8086b085d0f51c30d90b70bdf7d29dcdb274a3d28849360ccc9e1731487f0179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
